version: "3.9"

services:

  db:
    image: postgres:15-alpine

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"


    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/init/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql


    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .

    container_name: absence_app

    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      ABSENCE_THRESHOLD: ${ABSENCE_THRESHOLD}

    ports:
      - "8080:8080"

    restart: no

volumes:
  postgres_data: